# https://nixpacks.com/docs/configuration/file
# set up some variables to minimize annoyance
[variables]

# download caddy from nix
[phases.caddy]
    dependsOn = ['setup'] # make sure this phase runs after the default 'setup' phase
    nixpkgsArchive = '8b27c1239e5c421a2bbc2c65d52e4a6fbf2ff296' # Caddy v2.8.4 - https://github.com/NixOS/nixpkgs/commit/8b27c1239e5c421a2bbc2c65d52e4a6fbf2ff296
    nixPkgs = ['caddy'] # install caddy as a nix package

# format the Caddyfile with fmt
[phases.fmt]
    dependsOn = ['caddy'] # make sure this phase runs after the 'caddy' phase so that we know we have caddy downloaded
    cmds = ['caddy fmt --overwrite Caddyfile'] # format the Caddyfile to fix any formatting inconsistencies

# start the caddy web server
[start]
    cmd = 'exec caddy run --config Caddyfile --adapter caddyfile 2>&1' # start caddy using the Caddyfile config and caddyfile adapter