name: snapster-dev
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: snapster
      MINIO_ROOT_PASSWORD: snapster
    entrypoint: minio server /data --console-address ":9001"
    volumes:
      - snapster-minio-data:/data

volumes:
  snapster-minio-data:
