name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build backend
        run: yarn build:backend
        env:
          JWT_SECRET: test-jwt-secret-for-ci
          BACKEND_PORT: 3001
          COOKIE_DOMAIN: localhost
          FRONTEND_URL: http://localhost:3000
          GOOGLE_CLIENT_ID: test-client-id
          GOOGLE_CLIENT_SECRET: test-client-secret
          SALT: 10
          STORAGE_ENDPOINT: localhost
          STORAGE_PORT: 9000
          STORAGE_ACCESS_KEY: minioadmin
          STORAGE_SECRET_KEY: minioadmin
          STORAGE_DEFAULT_BUCKET: default
          STORAGE_USE_SSL: false
          UPLOAD_MAX_FILE_SIZE: 5248000

      - name: Build frontend
        run: yarn build:frontend
        env:
          VITE_BACKEND_URL: http://localhost:3001 